### ISSUE TITLE
Blank screen 

### ISSUE THREAD

**Issue by johnmc1979** [TOAD-Joey/TOAD-DA-Sync-Backup#4]
Howdy,
I'm in the 7 day free trial and just installed the plugin. When I click on the plugin in extra features it opens to a blank screen. 

What do you think could be the cause of the blank screen. It's like the area where it should load is empty.

Also, does it connect to google drive?

The buy button link to paypal doesn't work on your site either (and possible the contact form too).

Thanks

John

**Comment by TOAD-Joey** [comment]
Hi John,

Thanks for trying out the plugin. The plugin itself won't support Google Drive because GDrive doesn't support rsync without any third-party plugins. We can't support any services without the use of rsync because the backups are incremental. 

About the blank screen; it seems that you are missing one of the requirements, like IonCube for instance, [please check the requirements page.](https://github.com/TOAD-Joey/TOAD-DA-Sync-Backup/wiki/Requirements)

**Comment by johnmc1979** [comment]
Hi Joey,
I checked the requirements and the only thing missing is the licence key which I can't enter as the page doesn't load. 
Did you want me to send you a message or email with details so that you could take a look?

**Comment by TOAD-Joey** [comment]
Hi John, you (or any other) can add me on skype; info@toadsoftware.nl. Let me know if you still have issues.

**Comment by johnmc1979** [comment]
All solved. TOAD-Joey was fantastic. It turned out to be my install of ioncube loader, so nothing at all wrong with the plugin. Get into it. Support is fantastic and it's the best possible way to backup your data
